version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: devmons-postgres
    environment:
      POSTGRES_DB: devmons
      POSTGRES_USER: devmons
      POSTGRES_PASSWORD: devmons123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devmons"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devmons-network

volumes:
  postgres_data:
    driver: local

networks:
  devmons-network:
    driver: bridge

