spring:
  application:
    name: devmons

  datasource:
    url: jdbc:postgresql://localhost:5432/devmons
    username: devmons
    password: devmons
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-change-this-in-production-minimum-256-bits}
  expiration: 28800000 # 8 hours in milliseconds

# Application Configuration
app:
  email:
    verification:
      expiration: 86400000 # 24 hours
    password-reset:
      expiration: 86400000 # 24 hours
  security:
    max-login-attempts: 5
    lockout-duration: 900000 # 15 minutes

